/*
 Roundtable
 (c) 2021 Nikola Sibalic
*/
function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];a=b?b.call(a):{next:aa(a)};for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
function ca(a,b,c,d,g){document.getElementById("confirmmessage").innerHTML=a;document.getElementById("bno").value=b;document.getElementById("bno").onclick=function(){document.getElementById("confirmd").style.display="none";c()};document.getElementById("byes").value=d;document.getElementById("byes").onclick=function(){document.getElementById("confirmd").style.display="none";g()};document.getElementById("confirmd").style.height=window.innerHeight+"px";document.getElementById("confirmd").style.width=
window.innerWidth+"px";document.getElementById("confirmd").style.display="flex"}
function da(a){a?(document.getElementById("intro").style.display="none",document.getElementById("intro3").style.display="none"):(a=document.createElement("img"),a.src=roundTableServer+"/api/qrcode/"+room,document.getElementById("qr").innerHTML="",document.getElementById("qr").appendChild(a),a=document.createElement("input"),a.setAttribute("type","text"),a.classList.add("text"),a.value=roundTableServer+"#"+room,a.id="elink",document.getElementById("rlink").appendChild(a),document.getElementById("intro3").style.display=
"none",document.getElementById("intro4").style.display="block",ea(),document.getElementById("bstart").addEventListener("click",function(){document.getElementById("intro").style.display="none";document.getElementById("intro4").style.display="none"}))}function ea(){var a=document.getElementById("elink");a.select();a.setSelectionRange(0,99999);document.execCommand("copy")};var fa=!1,e=0,f=document.getElementById("cursor"),ha=null,ia=null,ja=null,ka=null,h=null,la=null,ma=null,k=null,na=null,oa=null,pa=!1;
function p(){if(roundTable)qa();else{ra=Math.min(200,.2*Math.max(window.innerWidth*window.innerHeight));var a=document.getElementById("slidespace");a.style.height=window.innerHeight+"px";a.style.width=.8*window.innerWidth+"px";a.style.marginLeft=.1*window.innerWidth+"px";a.style.fontSize="1em";document.body.style.fontSize=Math.round(window.innerWidth/1920*40)+"px";if(r){var b=document.getElementById("sketchpad");b.setAttribute("width",.8*window.innerWidth+"px");b.setAttribute("height",window.innerHeight+
"px")}fa?document.getElementById("controlspace").children[1].classList.add("fullscreenopened"):document.getElementById("controlspace").children[1].classList.remove("fullscreenopened");b=document.getElementById("zoomedim");null!==b&&(b.style.width=.8*window.innerWidth+"px",b.style.height=window.innerHeight+"px");if(b=document.getElementById("drawinghelp"))b.parentElement.removeChild(b),sa();ta();if(a=document.getElementById("presentervideo")){b=Math.round(.1*window.innerWidth);var c=Math.round(b/640*
480);a.setAttribute("width",b+"px");a.setAttribute("height",c+"px")}a=document.getElementsByClassName("demoCameraStream");for(var d=0;d<a.length;d+=1){var g=document.getElementById("demovideo"+d);g&&(b=g.parentElement.clientWidth,c=g.parentElement.clientHeight,g.setAttribute("width",b+"px"),g.setAttribute("height",c+"px"))}}}
function ua(){var a=wa("a");void 0!==a&&(roundTableAuth=a);a=wa("r");void 0!==a&&(roundTableServer=decodeURIComponent(a));a=wa("l");void 0!==a&&(room=a);document.getElementById("slidespace").addEventListener("mousemove",xa);document.getElementById("slidespace").addEventListener("mouseleave",ya);document.getElementById("slidespace").addEventListener("touchmove",za);document.getElementById("slidespace").addEventListener("touchend",ya);k=Aa;window.onkeyup=function(d){if(!roundTable&&"block"!=document.getElementById("controlspace").children[16].style.display){var g=
d.keyCode;d.preventDefault();39===g?Ba():37===g&&Ca()}};window.addEventListener("resize",p);window.addEventListener("popstate",function(){Da();t(!0)});a=document.getElementById("controlspace");var b=document.getElementById("cameraspace"),c=document.getElementById("roundtable_participants");leftHanded?(a.style.right="0px",b.style.left="0px",c.style.left="0px"):(a.style.left="0px",b.style.right="0px",c.style.right="0px");a=a.children;a[0].style.display="none";a[0].addEventListener("click",function(){null!=
roundTableExit&&roundTableExit()});a[1].addEventListener("click",function(d){if(fa)document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.webkitCancelFullScreen?document.webkitCancelFullScreen():document.msExitFullscreen&&document.msExitFullscreen(),fa=!1;else{var g=document.documentElement;fa=!0;g.requestFullscreen?g.requestFullscreen():g.mozRequestFullScreen?g.mozRequestFullScreen():g.webkitRequestFullScreen?g.webkitRequestFullScreen():
g.msRequestFullscreen?g.msRequestFullscreen():fa=!1}d.preventDefault()});a[2].onclick=function(d){Ba();d.preventDefault()};a[3].onclick=function(d){Ca();d.preventDefault()};a[4].addEventListener("click",function(d){v();d.preventDefault()});a[4].style.display="none";a[5].addEventListener("click",function(d){document.getElementById("controlspace").children[4].style.backgroundImage='url("./caroline/images/draw.png")';Ea();d.preventDefault()});a[6].children[0].style.backgroundColor="rgb(0,0,0)";a[6].addEventListener("mousedown",
function(d){w=[0,0,0,255];document.getElementById("cursor").children[0].style.backgroundColor="rgba(0,0,0,0.7)";d.preventDefault();if(d=document.getElementById("textannotation"))d.style.color="rgb("+w[0]+","+w[1]+","+w[2]+")"});a[6].style.display="none";a[7].children[0].style.backgroundColor="rgb(231,70,73)";a[7].addEventListener("mousedown",function(d){w=[231,70,73,255];document.getElementById("cursor").children[0].style.backgroundColor="rgba(231,70,73,0.7)";d.preventDefault();if(d=document.getElementById("textannotation"))d.style.color=
"rgb("+w[0]+","+w[1]+","+w[2]+")"});a[7].style.display="none";a[8].children[0].style.backgroundColor="rgb(246,209,84)";a[8].addEventListener("mousedown",function(d){w=[246,209,84,255];document.getElementById("cursor").children[0].style.backgroundColor="rgba(246,209,84,0.7)";d.preventDefault();if(d=document.getElementById("textannotation"))d.style.color="rgb("+w[0]+","+w[1]+","+w[2]+")"});a[8].style.display="none";a[9].children[0].style.backgroundColor="rgb(58,124,242)";a[9].addEventListener("mousedown",
function(d){w=[58,124,242,255];document.getElementById("cursor").children[0].style.backgroundColor="rgba(58,124,242,0.7)";d.preventDefault();if(d=document.getElementById("textannotation"))d.style.color="rgb("+w[0]+","+w[1]+","+w[2]+")"});a[9].style.display="none";a[10].style.display="none";a[10].addEventListener("click",function(d){x=10<x?Math.round(.9*x):Math.round(x-1);1>x&&(x=1);Fa=Math.max(2,Math.round(.05*x));d.target.innerHTML=x+" px";f.children[0].style.height=x+"px";f.children[0].style.width=
x+"px";null!=ha&&clearTimeout(ha);ha=setTimeout(function(){document.getElementById("controlspace").children[10].innerHTML=""},1E3);d.preventDefault()});a[11].style.display="none";a[11].addEventListener("click",function(d){x=10<x?Math.round(1.1*x):Math.round(x+1);60<x&&(x=60);Fa=Math.max(2,Math.round(.05*x));d.target.innerHTML=x+" px";f.children[0].style.height=x+"px";f.children[0].style.width=x+"px";null!=ia&&clearTimeout(ia);ia=setTimeout(function(){document.getElementById("controlspace").children[11].innerHTML=
""},1E3);d.preventDefault()});a[12].addEventListener("click",function(d){document.getElementById("controlspace").children[4].style.backgroundImage='url("./caroline/images/text.png")';Ga();document.getElementById("slidespace").addEventListener("click",Ha,!0);d.preventDefault()});presenter||(a[13].style.display="none");a[13].addEventListener("click",function(d){Ia();d.preventDefault()});a[14].style.display="none";a[14].addEventListener("click",function(){document.getElementById("selectedimage").click()});
document.getElementById("selectedimage").addEventListener("change",Ja);a[15].style.display="none";a[15].addEventListener("click",function(d){d.preventDefault();null==Ka&&null==y[B].file?La():null!=y[B].file?ca("Do you want to download shared source code file (without annotations)<br> or annotated image of the full source code?","Download shared file",function(){Ma(y[B].file,Na()+"-code"+y[B].b,"text/plain")},"Get annotated code as png",La):ca("Do you want to download shared PDF (without annotations)<br> or annotated image of current view (single page)?",
"Download shared PDF",function(){Ma(Ka,Na()+"-PDF.pdf","application/pdf")},"Get current annotated view",La)});a[16].style.display="none";a[16].addEventListener("mousedown",function(d){C=Math.min(Math.round(1.1*C*100)/100,6);var g=document.getElementById("textannotation");null!=g&&(g.style.fontSize=C+"em");d.target.innerHTML=C;null!=ja&&clearTimeout(ja);ja=setTimeout(function(){document.getElementById("controlspace").children[16].innerHTML=""},1E3);d.preventDefault()});a[17].style.display="none";a[17].addEventListener("mousedown",
function(d){C=Math.max(Math.round(C/1.1*100)/100,.35);var g=document.getElementById("textannotation");null!=g&&(g.style.fontSize=C+"em");d.target.innerHTML=C;null!=ka&&clearTimeout(ka);ka=setTimeout(function(){document.getElementById("controlspace").children[17].innerHTML=""},1E3);d.preventDefault()});a[18].style.display="none";a[18].addEventListener("click",function(d){if(0<D){roundTable&&E.emit("send_room",{action:"remove",id:D,username:username,room:room});var g=document.getElementById("l"+D+"-"+
username);g.parentElement.removeChild(g);--D}d.preventDefault()});a[19].style.display="none";a[19].onclick=function(d){E.emit("send_room",{action:"clearAll",username:username,room:room});F();d.preventDefault()};a[20].style.display="none";a[20].addEventListener("click",function(){E.emit("send_room",{action:"surface_new",id:B,room:room});Oa(B)});a=document.getElementById("slidespace");a.addEventListener("mousedown",Pa,!1);a.addEventListener("mouseup",Qa,!1);a.addEventListener("touchstart",Pa,!1);a.addEventListener("touchend",
Qa,!1);a=document.getElementById("cameraspace").children[0];a.addEventListener("click",function(){Ra()});a=window.location.hash.substr(1);document.getElementById("cameraspace").style.display=presenter?"block":"none";document.getElementById("controlspace").style.display="block";document.getElementById("slidespace").style.display="block";na=function(){};!roundTable&&(0==a.indexOf("slide")||10>a.length)?presenter&&""!=presentationServer?(username="Lecturer",Sa()):!presenter&&roundTableAuth?(username=
"Audience",Ta()):(Da(),t()):Ia()}function Ta(){E=io(roundTableServer,{query:{auth2:roundTableAuth}});Ua();window.onbeforeunload=function(){return"Are you sure you want to stop following presentation?"}}
function Va(){e=-1;document.getElementById("slidespace").innerHTML="<div class='slide'><div class='spancenter'><h2>Follow presentation with your annotations on</h2><div id='qr'>connecting to server...</div></div></div>";document.getElementById("qr").innerHTML="<img src='"+roundTableServer+"/api/qrpres/?q="+encodeURIComponent(presentationServer)+"&a="+roundTableAuth+"&r="+encodeURIComponent(roundTableServer)+"&l="+encodeURIComponent(room)+"' ><br><input value='"+presentationServer+"?a="+roundTableAuth+
"&r="+encodeURIComponent(roundTableServer)+"&l="+encodeURIComponent(room)+"' >"}function Sa(){Wa=!0;E=io(roundTableServer,{query:{pkey:roundTableAuth,site:presentationServer}});Ua();e=-1;window.onbeforeunload=function(){return"Are you sure you want to stop current presentation?"}}var G=1E6;
function Ua(){E.on("connect",function(){pa=!0;-1==username.indexOf("=")&&(username=username+"="+E.id);null==room&&(room=window.location.hash.substr(1));var a=!0;if(""==room||0==room.indexOf("slide"))room=E.id+"L",Wa=!0,H=.8*window.innerWidth,I=window.innerHeight,p(),a=!1,document.getElementById("roundtable_participants").innerHTML=" Participants: <span id='"+username.substr(username.indexOf("=")+1)+"'>"+username.substr(0,username.indexOf("="))+"</span>";Wa||(null!=h&&clearTimeout(h),h=setTimeout(na,
6E3));E.emit("join_room",{username:username,room:room});presenter?(Da(),0==e?Va():(t(),null!=room&&E.emit("send_room",{action:"maxslide",i:e,room:room})),E.on("presentationstate",function(b){E.emit("presentationstate",{to:b.from,slideIndex:Math.max(e,0),roundtable:roundTable})})):(E.on("presentationstate",function(b){G=e=b.slideIndex;t();b.roundtable&&Ia()}),E.emit("presentationstate",{from:E.id,to:room.substr(0,room.length-1)}));null!=roundTableCallBack&&roundTableCallBack(a)});E.on("initial_response",
function(a){presenter||(e=G=0,t());roundTableAuth=a.token});E.io.on("reconnect_attempt",function(){E.io.opts.query={auth2:roundTableAuth}});E.on("connect_error",function(){J("Connection error.")});E.on("new_user",function(a){if(a.username!=username){var b=document.getElementById("roundtable_participants");if(null==document.getElementById(a.sid)){var c=" Participants: ";""!=b.innerHTML&&(c+=b.innerHTML.substr(15));b.innerHTML=c+"<span id='"+a.sid+"'>"+a.username.substr(0,a.username.indexOf("="))+"</span>"}Wa&&
E.emit("send_user",{userid:a.username.substr(a.username.indexOf("=")+1),action:"introduceNewMember",sid:a.sid,list:b.innerHTML.substr(15),tableWidth:H,tableHeight:I})}});E.on("user_disconnected",function(a){E.emit("room_user_left",{userid:a.userid,room:room,action:"memberLeft"})});E.on("m",Xa);E.on("update_state",Ya);E.on("quizanswers",function(a){for(;a.qid>=K.length;)K.push({});K[a.qid][a.u]=a.a;null!=Za&&Za==a.qid&&$a(a.qid)});E.io.on("reconnect_attempt",function(){E.io.opts.query={auth2:roundTableAuth}});
E.on("connect_error",function(){J("Connection error.")})}
function $a(a){if(0==ab.length){var b=document.getElementById("responseCount"+a);null!=b&&(b.innerHTML="<input id='seeresults' data-qid="+a+" type='button' value='See responses ("+Object.keys(K[a]).length+")'>",document.getElementById("seeresults").onclick=function(){var c=document.getElementsByClassName("quizq");bb="";for(var d=0;d<c.length;d+=1)bb+=c[d].parentElement.outerHTML;for(ab=[];0<document.getElementsByClassName("quiza").length;)c=document.getElementsByClassName("quiza")[0],c.classList.add("resultanswer"),
c.classList.remove("quiza"),ab[parseInt(c.dataset.aid,10)]=c.outerHTML;cb(a)})}else cb(a)}
function cb(a){db();document.getElementById("slidespace").innerHTML="<div class='slide'><div class='gridslide' style='grid-template-columns: repeat(2, 1fr); grid-template-rows: repeat(3, 33.33%)'>"+bb+"<div id='resultspace' style='padding:0.3em;grid-column: 1 / 3; grid-row: 2 / 4; font-size:1.00e+00m'></div></div>";for(var b={},c=Object.keys(K[a]).length,d=0;d<c;d+=1){for(var g=Object.keys(K[a])[d],m="",l=0;l<K[a][g].length;l+=1)m+=K[a][g][l];b[m]=m in b?b[m]+1/c:1/c}c=document.createElement("table");
c.classList.add("quizresultview");for(d=0;d<Object.keys(b).length;d+=1){m=document.createElement("tr");g=Object.keys(b)[d];var n="",q=g.split("");for(l=0;l<q.length;l+=1)n+=ab[parseInt(q[l],10)]+"&nbsp;";m.innerHTML="<td>"+n+"</td><td><div class='histogram' style='width:"+100*b[g]+"%'>&nbsp;&nbsp;"+parseInt(b[g]*Object.keys(K[a]).length,10)+"</div></td>";c.appendChild(m)}document.getElementById("resultspace").appendChild(c);b=document.getElementById("responseCount"+a);null!=b&&(b.innerHTML="<input id='seeresults' data-qid="+
a+" type='button' value='Go back to questions ("+Object.keys(K[a]).length+")'>",document.getElementById("seeresults").onclick=function(){t(!0)})}var K=[],Za=null,ab=[],bb=null;function wa(a){for(var b=window.location.search.substring(1).split("&"),c=0;c<b.length;c++){var d=b[c].split("=");if(d[0]==a)return d[1]}}
function Oa(a){a+=1;y=ba(y.slice(0,a)).concat([{g:[],c:null,f:1,h:[],j:null,file:null,b:null,timestamp:0,scroll:[0,0]}],ba(y.slice(a)));var b=document.getElementById("controlspace").children;1<y.length?(b[2].style.display="block",b[3].style.display="block"):(b[2].style.display="none",b[3].style.display="none");eb(a)}
function fb(){if(roundTable){var a=[];gb();y[B].f=L;null!=M&&(y[B].scroll=[M.scrollTop,M.scrollLeft]);for(;0<document.getElementById("slidespace").children.length;)a.push(document.adoptNode(document.getElementById("slidespace").children[0]));y[B].g=a;y[B].c=Ka;y[B].h=N;y[B].j=M}}
function eb(a){fb();M=null;B=a;a=O;N=y[B].h;Ka=y[B].c;null==y[B].g&&null!=y[B].c&&(y[B].c=new Blob([y[B].c]));null==y[B].g&&null!=y[B].file&&(y[B].file=new Blob([y[B].file]));if(null!=y[B].c)L=y[B].f,hb(y[B].c),v(),O=!1;else{ib();if(null!=y[B].g&&0<y[B].g.length)for(document.getElementById("slidespace").innerHTML="";0<y[B].g.length;)document.getElementById("slidespace").appendChild(y[B].g.pop());a?(jb(),Ea()):(kb(),v());O=a;L=1;M=y[B].j;null==y[B].g&&null!=y[B].file&&(a=/(\.jpg|\.jpeg|\.png|\.gif)$/i,
a.exec(y[B].b)&&lb(y[B].file,y[B].b),a=/(\.sh|\.c|\.cpp|\.h|\.cc|\.c\+\+|\.cxx|\.hxx|\.cs|\.css|\.txt|\.diff|\.go|\.html|\.xml|\.json|\.java|\.js|\.less|\.lua|\.make|\.gmk|\.md|\.php|\.pl|\.py|\.sql|\.r|\.rb|\.rs|\.swift|\.vb|\.yaml|\.f|\.f95|\.f90|\.f03|\.f08|\.ftn|\.for|\.mat|\.jl|\.m|\.nb|\.wl)$/i,a.exec(y[B].b)&&mb(y[B].file,y[B].b),a=/(\.ipynb)$/i,a.exec(y[B].b)&&nb(y[B].file));ob()}pb();null!=M&&(M.scrollTop=y[B].scroll[0],M.scrollLeft=y[B].scroll[1]);J("Surface "+(B+1)+" of "+y.length+".")}
function J(a){var b=document.getElementById("notify");b.children[0].innerHTML=a;b.style.display="block";null!=ma&&clearTimeout(ma);ma=setTimeout(function(){document.getElementById("notify").style.display="none"},1E3)}function qb(a){var b=Na()+".png",c=document.createElement("a");"string"===typeof c.download?(c.href=a,c.download=b,document.body.appendChild(c),c.click(),document.body.removeChild(c)):window.open(a)}
function rb(a){a.target.style.height="auto";a.target.style.height=a.target.scrollHeight+"px"}function sb(){for(var a=document.getElementsByClassName("sframe"),b=0;b<a.length;b+=1)a[b].classList.add("canvas-inactive");a=document.getElementsByClassName("simage");for(b=0;b<a.length;b+=1)a[b].classList.add("canvas-inactive");if(null!=M)for(M.removeEventListener("pointerdown",tb),a=M.getElementsByTagName("a"),b=0;b<a.length;b+=1)a[b].classList.add("canvas-inactive")}
function Ha(a){var b=document.createElement("textarea");b.id="textannotation";b.classList.add("textannotation");b.setAttribute("placeholder","Type text or $LaTeX$...");null==M?(b.style.fontSize=C+"em",b.style.left=(a.clientX-.1*window.innerWidth)/P+"px",b.style.top=a.clientY/P+"px",document.getElementById("slidespace").appendChild(b)):(b.style.fontSize=C/.76+"em",b.style.left=(a.clientX-.1*window.innerWidth)/P+M.scrollLeft+"px",b.style.top=a.clientY/P+M.scrollTop+"px",M.appendChild(b));b.style.height=
b.scrollHeight+"px";b.style.width=roundTable?H+(.1*window.innerWidth-a.clientX)/P+"px":.9*window.innerWidth-a.clientX+"px";b.style.color="rgb("+w[0]+","+w[1]+","+w[2]+")";b.addEventListener("input",rb,!1);b.focus();document.getElementById("slidespace").removeEventListener("click",Ha,!0);b.addEventListener("blur",ub)}
function Ga(){for(var a=document.getElementById("controlspace").children,b=4;16>b;b+=1)a[b].style.display="none";a[4].style.display="block";a[5].style.display="none";a[6].style.display="block";a[7].style.display="block";a[8].style.display="block";a[9].style.display="block";a[16].style.display="block";a[17].style.display="block";a[18].style.display="block";a[19].style.display="none";a[20].style.display="none";sb()}
function ub(a){a=a.target;var b=a.value;b=vb(b).replace(/\r?\n/g,"<br>");var c=a.parentElement;if(""==b)c.removeChild(a),v();else{var d=document.createElement("div");d.classList.add("textannotation");d.style.left=a.style.left;d.style.top=a.style.top;d.style.height="auto";d.style.width="auto";d.style.maxWidth=a.style.width;d.style.fontSize=a.style.fontSize;d.innerHTML=b;var g=a.style.color;d.style.color=g;a.parentElement.removeChild(a);D+=1;d.id="l"+D+"-"+username;d.addEventListener("dblclick",wb,
!1);d.dataset.s=b;c.append(d);MathJax.typesetClear();MathJax.typesetPromise();v();roundTable&&E.emit("send_room",{action:"text",id:D,text:b,fontSize:C,color:g,x:parseFloat(a.style.left.replace("px","")),y:parseFloat(a.style.top.replace("px","")),username:username,room:room},function(m){y[B].timestamp=m})}}
function wb(a){Ga();var b=a.target,c=document.createElement("textarea");c.id="textannotation";c.classList.add("textannotation");c.setAttribute("placeholder","Type text or $LaTeX$...");c.style.left=b.style.left;c.style.top=b.style.top;c.style.fontSize=b.style.fontSize;c.value=b.dataset.s.replace(/<br>/g,"\n").replace(/&amp;/g,"&").replace(/&lt;/,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#039;/g,"'");c.style.color=b.style.color;roundTable&&E.emit("send_room",{action:"deleteAnnotation",
id:b.id,room:room},function(d){y[B].timestamp=d});xb(b.id);null===M?document.getElementById("slidespace").appendChild(c):M.appendChild(c);c.style.height=c.scrollHeight+"px";c.style.width=roundTable?H+(.1*window.innerWidth-a.clientX)/P+"px":.9*window.innerWidth-a.clientX+"px";c.addEventListener("input",rb,!1);c.focus();document.getElementById("slidespace").removeEventListener("click",Ha,!0);c.addEventListener("blur",ub)}
function xb(a){var b=document.getElementById(a);b.parentElement.removeChild(b);b=parseInt(a.substr(1,a.indexOf("-")),10);a=a.substr(a.indexOf("-"));for(b+=1;null!=document.getElementById("l"+b+a);)document.getElementById("l"+b+a).id="l"+(b-1)+a,b+=1;a.substr(1)==username&&--D}var E,Wa=!1,P=1,I=5,H=5;
function Ja(a,b){F();void 0===b&&(b=document.getElementById("selectedimage").files[0]);5<b.size/1024/1024?alert("Only images up to 5 MB can be shared in this way. Selected image has "+Math.round(100*b.size/1024/1024)/100+" MB."):(a=/(\.jpg|\.jpeg|\.png|\.gif)$/i,a.exec(b.name)?(R=a.exec(b.name)[0],E.emit("send_room",{action:"image",file:b,extension:R,username:username,room:room},function(c){y[B].timestamp=c}),lb(b,R)):(a=/(\.pdf)$/i,a.exec(b.name)?(L=1,hb(b),E.emit("send_room",{action:"pdf",file:b,
username:username,room:room},function(c){y[B].timestamp=c})):(a=/(\.sh|\.c|\.cpp|\.h|\.cc|\.c\+\+|\.cxx|\.hxx|\.cs|\.css|\.txt|\.diff|\.go|\.html|\.xml|\.json|\.java|\.js|\.less|\.lua|\.make|\.gmk|\.md|\.php|\.pl|\.py|\.sql|\.r|\.rb|\.rs|\.swift|\.vb|\.yaml|\.f|\.f95|\.f90|\.f03|\.f08|\.ftn|\.for|\.mat|\.jl|\.m|\.nb|\.wl)$/i,a.exec(b.name)?(R=a.exec(b.name)[0],E.emit("send_room",{action:"code",file:b,extension:R,username:username,room:room},function(c){y[B].timestamp=c}),mb(b,R)):(a=/(\.ipynb)$/i,
a.exec(b.name)?(R=a.exec(b.name)[0],E.emit("send_room",{action:"ipynb",file:b,extension:R,username:username,room:room},function(c){y[B].timestamp=c}),nb(b)):alert("Invalid file type for sharing.\n Allowed types are .jpg, .jpeg, .png, .gif, .pdf, .ipynb .sh, .c, .cpp, .h, .cc, .c++, .cxx, .hxx, .cs, .css, .txt, .diff, .go, .html, .xml, .json, .java, .js, .less, .lua, .make, .gmk, .md, .php, .pl, .py, .sql, .r, .rb, .rs, .swift, .vb, .yaml, .f, .f95, .f90, .f03, .f08, .ftn, .for, .mat, .jl, .m, .nb and .wl.")))))}
function lb(a,b){ib();y[B].file=a;y[B].b=b;b=document.getElementById("slidespace").getElementsByClassName("slide")[0];var c=document.createElement("img");c.classList.add("simage");c.addEventListener("mousedown",yb);c.setAttribute("draggable","false");c.src=URL.createObjectURL(a);b.appendChild(c);ob()}
function nb(a){var b=new FileReader;b.addEventListener("loadend",function(c){zb();document.getElementById("slidespace").innerHTML="<div class='slide'> <div id='ipynb'></div></div>";var d=nbv_constructor(document,{md:window.markdownit().use(window.markdownitMathjax()),hljs:hljs});y[B].file=a;y[B].b=".ipynb";d.render(JSON.parse(c.target.result),document.getElementById("ipynb"));M=document.getElementById("ipynb");M.style.fontSize=Math.round(H/.8*.76/1920*40)+"px";M.style.lineHeight=Math.round(25.8667/
27.2292*(H/.8)/1920*40)+"px";M.scrollTop=y[B].scroll[0];M.scrollLeft=y[B].scroll[1];d=document.getElementById("slidespace").getElementsByTagName("code");for(c=0;c<d.length;c+=1)d[c].style.fontSize=Math.round(H/.8*.65/1920*40)+"px",d[c].style.lineHeight=Math.round(25.8667/27.2292*(H/.8)/1920*40)+"px";d=document.getElementsByTagName("div");for(c=0;c<d.length;c+=1)d[c].style.lineHeight=Math.round(30/27.2292*(H/.8)/1920*40)+"px";d=document.getElementsByTagName("p");for(c=0;c<d.length;c+=1)d[c].style.lineHeight=
Math.round(30/27.2292*(H/.8)/1920*40)+"px";d=document.getElementsByTagName("pre");for(c=0;c<d.length;c+=1)d[c].style.lineHeight=Math.round(25.8667/27.2292*(H/.8)/1920*40)+"px";Ab();v();M.addEventListener("pointerdown",tb);M.addEventListener("scroll",Bb);ob();d=M.getElementsByTagName("img");for(c=0;c<d.length;c+=1)d[c].addEventListener("mousedown",yb),d[c].setAttribute("draggable","false"),d[c].addEventListener("load",function(){p()});p()});b.readAsText(a)}
function mb(a,b){var c=new FileReader;c.addEventListener("loadend",function(d){document.getElementById("slidespace").innerHTML="<div class='slide'> <pre><code class='language-"+Cb[b]+"'> "+vb(d.target.result)+"</pre></code></div>";hljs.highlightAll();y[B].file=a;y[B].b=b;M=document.getElementById("slidespace").getElementsByTagName("code")[0];M.style.fontSize=Math.round(H/.8*.76/1920*40)+"px";M.style.lineHeight=Math.round(25.8667/27.2292*(H/.8)/1920*40)+"px";M.scrollTop=y[B].scroll[0];M.scrollLeft=
y[B].scroll[1];Ab();v();p();M=document.getElementById("slidespace").getElementsByTagName("code")[0];M.addEventListener("pointerdown",tb);M.addEventListener("scroll",Bb);ob();d=document.getElementById("slidespace").getElementsByClassName("slide")[0];var g=document.createElement("div");g.classList.add("pdfcontrol");g.innerHTML='<button id="dark">Dark</button>  <button id="light">Light</button>';d.append(g);document.getElementById("light").addEventListener("click",function(){zb();E.emit("send_room",
{action:"code_light",username:username,room:room})});document.getElementById("dark").addEventListener("click",function(){Db();E.emit("send_room",{action:"code_dark",username:username,room:room})})});c.readAsText(a)}function Bb(a){oa==username&&E.emit("send_room",{action:"scroll",top:a.target.scrollTop,left:a.target.scrollLeft,username:username,room:room})}
function zb(){document.getElementById("codedarkcss").setAttribute("disabled","disabled");document.getElementById("codelightcss").removeAttribute("disabled")}function Db(){document.getElementById("codelightcss").setAttribute("disabled","disabled");document.getElementById("codedarkcss").removeAttribute("disabled")}
var M=null,Eb={top:0,left:0,x:0,y:0},R=null,Cb={".sh":"bash",".c":"c",".cpp":"c",".h":"c",".cc":"c",".c++":"c",".cxx":"c",".hxx":"c",".cs":"csharp",".css":"css",".txt":"txt",".diff":"diff",".go":"go",".html":"html",".xml":"xml",".json":"json",".java":"java",".js":"js",".less":"less",".lua":"lua",".make":"make",".gmk":"make",".md":"mf",".php":"php",".pl":"perl",".py":"python",".sql":"sql",".r":"r",".rb":"ruby",".rs":"rust",".swift":"swift",".vb":"vbnet",".yaml":"yaml",".f":"fortran",".f95":"fortran",
".f90":"fortran",".f03":"fortran",".f08":"fortran",".ftn":"fortran",".for":"fortran",".mat":"matlab",".jl":"julia",".m":"mathematica",".nb":"mathematica",".wl":"mathematica"};function tb(a){oa=username;Eb={left:M.scrollLeft,top:M.scrollTop,x:a.clientX,y:a.clientY};M.style.userSelect="none";document.addEventListener("pointermove",Fb);document.addEventListener("pointerup",Gb)}function Fb(a){var b=a.clientX-Eb.x;M.scrollTop=Eb.top-(a.clientY-Eb.y)/P;M.scrollLeft=Eb.left-b/P}
function Gb(){M.style.removeProperty("user-select");document.removeEventListener("pointermove",Fb);document.removeEventListener("pointerup",Gb)}
function gb(){var a=L;if(!Hb){for(var b=[];0<document.getElementsByClassName("textannotation").length;)b.push(document.adoptNode(document.getElementsByClassName("textannotation")[0]));var c="";null!=document.getElementById("sketchpad")&&(c=document.getElementById("sketchpad").innerHTML,document.getElementById("sketchpad").innerHTML="");N[a]={svg:c,text:b}}}
function ob(){var a=L;if(void 0!=N[a]){for(document.getElementById("sketchpad").innerHTML+=N[a].svg;0<N[a].text.length;)document.getElementById("sketchpad").parentElement.appendChild(N[a].text.pop());pb();MathJax.typesetClear();MathJax.typesetPromise()}}var N={};
function hb(a){ib();Ka=a;y[B].c=a;document.getElementById("slidespace").getElementsByClassName("slide")[0].innerHTML+='<canvas id="pdf-canvas"></canvas>';S=document.getElementById("pdf-canvas");Ib=S.getContext("2d");pdfjsLib.getDocument(URL.createObjectURL(a)).promise.then(function(b){Jb=b;if(1<Jb.numPages){b=document.getElementById("slidespace").getElementsByClassName("slide")[0];var c=document.createElement("div");c.classList.add("pdfcontrol");c.innerHTML='<button id="prev">&nbsp;&lt;&nbsp;&lt;&nbsp;</button> <span><span id="textpdfpage">1</span><input type="range" id="pdfpage" name="pdfPage"  min="1" max="1"><span> <button id="next">&nbsp;&gt;&nbsp;&gt;&nbsp;</button>';
b.append(c);document.getElementById("pdfpage").max=Jb.numPages;document.getElementById("pdfpage").addEventListener("change",function(){var d=parseInt(document.getElementById("pdfpage").value,10);gb();L=d;Kb(d)});document.getElementById("prev").addEventListener("click",Lb);document.getElementById("next").addEventListener("click",Mb)}Nb(L)})}var Ka=null,Jb=null,L=1,Hb=!1,Ob=null,S=null,Ib=null;
function Nb(a){y[B].f=L;Hb=!0;Jb.getPage(a).then(function(c){var d=c.getViewport({scale:1});d=c.getViewport({scale:Math.min(H/d.width,I/d.height)});S.height=d.height;S.width=d.width;S.style.height=d.height+"px";S.style.width=d.width+"px";S.style.marginLeft=(H-d.width)/2+"px";S.style.marginTop=(I-d.height)/2+"px";c.render({canvasContext:Ib,viewport:d}).promise.then(function(){Hb=!1;null!==Ob?(Nb(Ob),Ob=null):ob()})});var b=document.getElementById("pdfpage");null!=b&&(b.value=a)}
function Kb(a){Pb(a);E.emit("send_room",{action:"pdf_page",page:a,username:username,room:room},function(b){y[B].timestamp=b})}function Pb(a){document.getElementById("textpdfpage").innerHTML="pdf page "+a+" of "+Jb.numPages;document.getElementById("textpdfpage").style.display="inline-block";null!=la&&clearTimeout(la);la=setTimeout(function(){document.getElementById("textpdfpage").style.display="none"},1E3);Hb?Ob=a:Nb(a)}function Lb(){1>=L||(gb(),L--,Kb(L))}
function Mb(){L>=Jb.numPages||(gb(),L++,Kb(L))}function Na(){var a=new Date;return"roundtable_"+a.getFullYear()+"-"+(10>a.getMonth()?"0":"")+a.getMonth()+"-"+(10>a.getDate()?"0":"")+a.getDate()+"_at_"+(0>a.getHours()?"0":"")+a.getHours()+"-"+(0>a.getMinutes()?"0":"")+a.getMinutes()+"-"+a.getSeconds()}
function Ma(a,b,c){if(null!=a)if(a=new Blob([a],{type:c||"application/octet-stream"}),"undefined"!==typeof window.navigator.msSaveBlob)window.navigator.msSaveBlob(a,b);else{var d=window.URL.createObjectURL(a);a=document.createElement("a");a.style.display="none";a.href=d;a.setAttribute("download",b);"undefined"===typeof a.download&&a.setAttribute("target","_blank");document.body.appendChild(a);a.click();document.body.removeChild(a);setTimeout(function(){window.URL.revokeObjectURL(d)},100)}}
function La(){var a=document.getElementById("slidespace"),b=1980/window.innerWidth;null===M?html2canvas(a,{scale:b,logging:!1,useCORS:!0,allowTaint:!0,letterRendering:!0}).then(function(c){c=c.toDataURL("image/png");qb(c)}):(a.style.width=M.scrollWidth+"px",a.style.height=M.scrollHeight+"px",html2canvas(a,{scale:b,logging:!1,useCORS:!0,allowTaint:!0,width:M.scrollWidth,height:M.scrollHeight/.99}).then(function(c){c=c.toDataURL("image/png");qb(c);p()}))}
function F(){M=null;y[B].file=null;y[B].b=null;y[B].timestamp=0;y[B].f=1;Jb=Ka=null;L=1;Hb=!1;Ib=S=Ob=null;N=[];ib()}
function ib(){db();var a=document.getElementById("controlspace").children;a[0].style.display="block";a[1].style.display="none";a[11].style.display="block";a[13].style.display="none";a[14].style.display="block";a[15].style.display="block";a[19].style.display="block";a[20].style.display="block";a=document.getElementById("cameraspace").style.display="none";a=document.getElementById("slidespace");a.innerHTML="<div class='slide' ></div>";Ab();v();p();a=document.getElementById("slidespace").getElementsByClassName("slide")[0];
a.addEventListener("drop",function(b){b.preventDefault();b.dataTransfer.items?0<b.dataTransfer.items.length&&"file"===b.dataTransfer.items[0].kind&&Ja(b,b.dataTransfer.items[0].getAsFile()):0<b.dataTransfer.files.length&&Ja(b,b.dataTransfer.files[0])});document.addEventListener("dragover",function(b){b.preventDefault()});D=0}var y=[{g:[],c:null,f:1,h:[],j:null,file:null,b:null,timestamp:0,scroll:[0,0]}],B=0,Qb=!1;
function Ia(){var a=document.getElementById("controlspace").children;a[2].onclick=function(b){b.preventDefault();B<y.length-1?(eb(B+1),E.emit("send_room",{action:"surface_change",id:B,room:room})):J("This is last surface. Click on + to add more.")};a[2].setAttribute("title","Next surface");a[3].onclick=function(b){b.preventDefault();0<B?(eb(B-1),E.emit("send_room",{action:"surface_change",id:B,room:room})):J("This is the first surface.")};a[3].setAttribute("title","Previous surface");null==y||1==
y.length?(a[2].style.display="none",a[3].style.display="none"):(a[2].style.display="block",a[3].style.display="block");document.getElementById("roundtable_participants").style.display="block";Qb?(ib(),eb(B),roundTable=!0):(roundTable=!0,F());a[13].style.display="none";a[14].style.display="block";Qb=!0;pa?presenter?(E.emit("send_room",{action:"openroundtable",room:room}),a[0].onclick=Rb):a[0].onclick=function(){alert("Only lecturer can initiate leaving of Roundtable.")}:Sb()}
function Rb(){v();fb();r=!1;presenter&&E.emit("send_room",{action:"closeroundtable",room:room});var a=document.getElementById("controlspace").children;a[0].style.display="none";a[1].style.display="block";a[2].onclick=function(b){Ba();b.preventDefault()};a[2].setAttribute("title","Next surface");a[3].onclick=function(b){Ca();b.preventDefault()};a[3].setAttribute("title","Previous surface");a[2].style.display="block";a[3].style.display="block";presenter&&(a[13].style.display="block");a[14].style.display=
"none";a[15].style.display="none";a[19].style.display="none";a[20].style.display="none";document.getElementById("roundtable_participants").style.display="none";presenter&&(document.getElementById("cameraspace").style.display="block");t();roundTable=!1;a=document.getElementById("slidespace");a.style.transform="scale(1,1)";p()}function Xa(a){Tb(a.x*P+.1*window.innerWidth,a.y*P,Ub(a.u))}
function Ya(a){if(roundTable)if("cursorhide"==a.action)Vb(Ub(a.username));else if("closeroundtable"==a.action)Rb();else if("line"==a.action){var b=document.createElementNS("http://www.w3.org/2000/svg","polyline");b.setAttribute("style",a.style);b.setAttribute("points",a.points);var c="l"+a.id+"-"+a.username;b.id=c;document.getElementById("sketchpad").appendChild(b);Wb(c);y[B].timestamp=a.t}else if("image"==a.action)c=new Blob([a.file]),F(),lb(c,a.extension),y[B].file=c,y[B].b=a.extension,y[B].timestamp=
a.t;else if("pdf"==a.action)F(),c=new Blob([a.file]),L=1,hb(c),y[B].timestamp=a.t;else if("pdf_page"==a.action)gb(),L=a.page,Pb(a.page),y[B].timestamp=a.t;else if("code"==a.action)c=new Blob([a.file]),F(),mb(c,a.extension),y[B].timestamp=a.t;else if("ipynb"==a.action)c=new Blob([a.file]),F(),nb(c),y[B].timestamp=a.t;else if("scroll"==a.action)oa=a.username,M.scrollTop=a.top,M.scrollLeft=a.left;else if("code_light"==a.action)zb();else if("code_dark"==a.action)Db();else if("blink_on"==a.action)Ub(a.username).classList.add("cursor_blinks");
else if("memberLeft"==a.action)b=document.getElementById(a.userid),b.parentElement.removeChild(b);else if("blink_off"==a.action)Ub(a.username).classList.remove("cursor_blinks");else if("remove"==a.action)c=a.id+"-"+a.username,b=document.getElementById("l"+c),b.parentElement.removeChild(b),y[B].timestamp=a.t;else if("clearAll"==a.action)F(),y[B].timestamp=a.t;else if("text"==a.action)c=a.id+"-"+a.username,b=document.createElement("div"),b.classList.add("textannotation"),b.classList.add("canvas-inactive"),
b.style.left=a.x+"px",b.style.top=a.y+"px",b.style.height="auto",b.style.width="auto",b.style.fontSize=a.fontSize+"em",b.innerHTML=a.text,b.style.color=a.color,b.id="l"+c,null==M?document.getElementById("slidespace").append(b):M.append(b),y[B].timestamp=a.t,MathJax.typesetClear(),MathJax.typesetPromise();else if("introduceNewMember"==a.action){null!=h&&clearTimeout(h);J("You have joined the Roundtable.");b=document.getElementById("roundtable_participants");b.innerHTML=" Participants: "+a.list;H=a.tableWidth;
I=a.tableHeight;qa();a=[];for(c=0;c<y.length;c+=1)a.push(y[c].timestamp);E.emit("send_user",{sid:E.id,action:"updateme",timestamps:a})}else if("surface_change"==a.action)eb(a.id);else if("surface_new"==a.action)Oa(a.id);else if("deleteAnnotation"==a.action)xb(a.id),y[B].timestamp=a.t;else if("updateme"==a.action){b=[];null!=M&&(y[B].scroll=[M.scrollTop,M.scrollLeft]);for(c=0;c<y.length;c+=1)c>=a.timestamps.length||y[c].timestamp>a.timestamps[c]?b.push({g:null,c:y[c].c,f:y[c].f,h:y[c].h,j:null,file:y[c].file,
b:y[c].b,timestamp:y[c].timestamp,scroll:y[c].scroll}):b.push(null);E.emit("send_user",{sid:a.sid,action:"update",update:b,currentSurface:B,surface:document.getElementById("slidespace").innerHTML})}else{if("update"==a.action){b=a.update;for(c=0;c<b.length;c+=1)c>=y.length&&y.push(b[c]),null!=b[c]&&(y[c]=b[c]);B=a.currentSurface;document.getElementById("slidespace").innerHTML=a.surface;Xb();null!=y[B].c?(y[B].c=new Blob([y[B].c]),L=y[B].f,gb(),hb(y[B].c)):null!=y[B].file&&(L=y[B].f,gb(),ib(),y[B].file=
new Blob([y[B].file]),a=/(\.jpg|\.jpeg|\.png|\.gif)$/i,a.exec(y[B].b)&&lb(y[B].file,y[B].b),a=/(\.sh|\.c|\.cpp|\.h|\.cc|\.c\+\+|\.cxx|\.hxx|\.cs|\.css|\.txt|\.diff|\.go|\.html|\.xml|\.json|\.java|\.js|\.less|\.lua|\.make|\.gmk|\.md|\.php|\.pl|\.py|\.sql|\.r|\.rb|\.rs|\.swift|\.vb|\.yaml|\.f|\.f95|\.f90|\.f03|\.f08|\.ftn|\.for|\.mat|\.jl|\.m|\.nb|\.wl)$/i,a.exec(y[B].b)&&mb(y[B].file,y[B].b),a=/(\.ipynb)$/i,a.exec(y[B].b)&&nb(y[B].file));v();a=document.getElementById("controlspace").children;1<y.length?
(a[2].style.display="block",a[3].style.display="block"):(a[2].style.display="none",a[3].style.display="none")}}else if("maxslide"==a.action)presenter||(G=Math.max(G,a.i),G==e+1?Ba():a.i>e&&J("You are behind the lecturer (slide "+e+"/"+G+")"));else if("openroundtable"==a.action)Ia();else if("memberLeft"==a.action)c=document.getElementById(a.userid),c.parentElement.removeChild(c);else if("introduceNewMember"==a.action){null!=h&&clearTimeout(h);c=document.getElementById("roundtable_participants");c.innerHTML=
" Participants: "+a.list;H=a.tableWidth;I=a.tableHeight;a=[];for(c=0;c<y.length;c+=1)a.push(y[c].timestamp);E.emit("send_user",{sid:E.id,action:"updateme",timestamps:a})}else if("updateme"==a.action){b=[];null!=M&&(y[B].scroll=[M.scrollTop,M.scrollLeft]);for(c=0;c<y.length;c+=1)c>=a.timestamps.length||y[c].timestamp>a.timestamps[c]?b.push({g:null,c:y[c].c,f:y[c].f,h:y[c].h,j:null,file:y[c].file,b:y[c].b,timestamp:y[c].timestamp,scroll:y[c].scroll}):b.push(null);E.emit("send_user",{sid:a.sid,action:"update",
update:b,currentSurface:B,surface:document.getElementById("slidespace").innerHTML})}else if("update"==a.action)for(b=a.update,c=0;c<b.length;c+=1)c>=y.length&&y.push(b[c]),null!=b[c]&&(y[c]=b[c])}
function Sb(){E=io(roundTableServer,{query:{auth:roundTableAuth}});E.on("connect",function(){-1==username.indexOf("=")&&(username=username+"="+E.id);room=window.location.hash.substr(1);var a=!0;if(""==room||0==room.indexOf("slide"))a=new Uint32Array(1),window.crypto.getRandomValues(a),room=E.id+a,history.pushState("","",location.protocol+"//"+location.host+location.pathname+"#"+room),Wa=!0,H=.8*window.innerWidth,I=window.innerHeight,p(),a=!1,document.getElementById("roundtable_participants").innerHTML=
" Participants: <span id='"+username.substr(username.indexOf("=")+1)+"'>"+username.substr(0,username.indexOf("="))+"</span>";Wa||(null!=h&&clearTimeout(h),h=setTimeout(na,6E3));E.emit("join_room",{username:username,room:room});null!=roundTableCallBack&&roundTableCallBack(a)});E.on("initial_response",function(a){roundTableAuth=a.token});E.io.on("reconnect_attempt",function(){E.io.opts.query={auth2:roundTableAuth}});E.on("connect_error",function(){J("Connection error.")});E.on("new_user",function(a){if(a.username!=
username){var b=document.getElementById("roundtable_participants");if(null==document.getElementById(a.sid)){var c=" Participants: ";""!=b.innerHTML&&(c+=b.innerHTML.substr(15));b.innerHTML=c+"<span id='"+a.sid+"'>"+a.username.substr(0,a.username.indexOf("="))+"</span>"}Wa&&E.emit("send_user",{userid:a.username.substr(a.username.indexOf("=")+1),action:"introduceNewMember",sid:a.sid,list:b.innerHTML.substr(15),tableWidth:H,tableHeight:I})}});E.on("user_disconnected",function(a){E.emit("room_user_left",
{userid:a.userid,room:room,action:"memberLeft"})});E.on("m",Xa);E.on("update_state",Ya)}function Ub(a){var b=document.getElementById("c"+a);null==b&&(b=document.createElement("div"),b.classList.add("cursor"),b.id="c"+a,b.innerHTML='<div class="cursor-icon"><div class="cursor-name">'+a.substr(0,a.indexOf("="))+"</div></div>",document.getElementById("cursor").parentElement.appendChild(b));return b}var Yb;
function Zb(a,b,c){var d;void 0===b?d=document.getElementById("cameraspace"):d=b;void 0===c&&(c=function(l){l.target&&$b(l.target.dataset.l,l.target.dataset.facing)});d.innerHTML="<p>Select camera:</p>";var g=document.createElement("ul"),m=0;a.forEach(function(l){"videoinput"===l.kind&&(m+=1)});1==m&&(b=document.createElement("li"),b.dataset.facing="user",b.innerHTML="Front facing",b.addEventListener("click",c),g.append(b),b=document.createElement("li"),b.dataset.facing="environment",b.innerHTML=
"Back facing",b.addEventListener("click",c),g.append(b));a.forEach(function(l){if("videoinput"===l.kind){var n=document.createElement("li");n.dataset.l=l.deviceId;l=l.label||"Camera "+m++;n.innerHTML=l;n.addEventListener("click",c);g.append(n)}});d.append(g)}function Ra(a,b){navigator.mediaDevices&&navigator.mediaDevices.getUserMedia&&navigator.mediaDevices.enumerateDevices().then(function(c){Zb(c,a,b)})}
function $b(a,b){var c={video:!0};void 0!==a&&""!=a?c={video:{deviceId:{exact:a}},audio:!1}:void 0!==b&&""!=b&&(c={video:{facingMode:b},audio:!1});document.getElementById("cameraspace").innerHTML="Adding camera...";navigator.mediaDevices&&navigator.mediaDevices.getUserMedia&&navigator.mediaDevices.getUserMedia(c).then(function(d){Yb=d;var g=document.createElement("video");g.id="presentervideo";var m=Math.round(.1*window.innerWidth),l=Math.round(m/640*480);g.setAttribute("width",m+"px");g.setAttribute("height",
l+"px");m=document.getElementById("cameraspace");m.innerHTML="";m.append(g);g.addEventListener("click",function(){Yb.getTracks().forEach(function(u){"live"==u.readyState&&u.stop()});var n=document.getElementById("cameraspace");n.removeChild(n.children[0]);var q=document.createElement("div");q.classList.add("camera");q.title="Add camera in the corner";q.addEventListener("click",function(){Ra()});n.append(q)});g.title="Click to stop camera";g.srcObject=d;g.play()})}
function Pa(){O||f.classList.contains("cursor_blinks")||(f.classList.add("cursor_blinks"),roundTable&&E.emit("send_room",{action:"blink_on",username:username,room:room}))}function Da(){var a=window.location.hash.substr(1);e=0;""!=a&&0==a.indexOf("slide")&&(a=a.substring(5),e=parseInt(a,10))}function Qa(){f.classList.contains("cursor_blinks")&&(f.classList.remove("cursor_blinks"),roundTable&&E.emit("send_room",{action:"blink_off",username:username,room:room}))}
var r=!1,O=!1,ac=null,bc,cc,dc=0,T,U,x=5,C=1,w=[0,0,0,255],Fa=2;
function v(){O&&(document.getElementById("sketchpad").classList.add("canvas-inactive"),O=!1,kb());var a=document.getElementById("controlspace").children;a[4].style.display="none";a[5].style.display="block";a[6].style.display="none";a[7].style.display="none";a[8].style.display="none";a[9].style.display="none";a[10].style.display="none";a[11].style.display="none";a[12].style.display="block";a[16].style.display="none";a[17].style.display="none";a[18].style.display="none";document.getElementById("cursor").children[0].style.backgroundColor=
"rgba(188, 40, 35, 0.7)";f.children[0].style.height="15px";f.children[0].style.width="15px";document.getElementById("slidespace").removeEventListener("click",Ha,!0);for(var b=document.getElementsByClassName("sframe"),c=0;c<b.length;c+=1)b[c].classList.remove("canvas-inactive");b=document.getElementsByClassName("simage");for(c=0;c<b.length;c+=1)b[c].classList.remove("canvas-inactive");if(null!=M)for(M.addEventListener("pointerdown",tb),b=M.getElementsByTagName("a"),c=0;c<b.length;c+=1)b[c].classList.remove("canvas-inactive");
roundTable?(a[14].style.display="block",a[15].style.display="block",a[19].style.display="block",a[20].style.display="block"):(a[14].style.display="none",a[19].style.display="none",presenter&&(a[13].style.display="block"))}
function Ab(){O=r=!0;var a=document.createElementNS("http://www.w3.org/2000/svg","svg");a.id="sketchpad";var b=M;null==b?(b=document.getElementById("slidespace"),a.setAttribute("width",Math.round(.8*window.innerWidth)),a.setAttribute("height",window.innerHeight)):(a.setAttribute("width",M.scrollWidth),a.setAttribute("height",M.scrollHeight));b.append(a);Xb();""!=drawingHelp&&(sa(),jb())}
function Xb(){var a=document.getElementById("sketchpad");a.addEventListener("mousedown",ec,!1);a.addEventListener("mousemove",fc,!1);window.addEventListener("mouseup",gc,!1);a.addEventListener("touchstart",hc,!1);a.addEventListener("touchmove",ic,!1);window.addEventListener("touchend",jc,!1)}function kb(){var a=document.getElementsByClassName("slide");0<a.length&&(a[0].style.backgroundColor="white")}
function jb(){if(""!=drawingHelp){var a=document.getElementsByClassName("slide");0<a.length&&(a[0].style.backgroundColor="transparent")}}
function sa(a,b){if(void 0==a||void 0==b)a=window.innerWidth,b=window.innerHeight;var c=document.getElementsByClassName("slide");if(!(1>c.length)){c=c[0];var d=Math.round(255-255*drawingHelpIntensity);d="rgb("+d+","+d+","+d+")";var g=document.createElementNS("http://www.w3.org/2000/svg","svg");g.id="drawinghelp";g.setAttribute("width",Math.round(.8*a));g.setAttribute("height",b);c.append(g);if("dots"==drawingHelp){c=Math.min(a,b)/15;var m=Math.max(3,c/15),l=Math.round(.8*a/c)+1,n=Math.round(b/c)+
1;for(a=1;a<l;a+=1)for(var q=1;q<n;q+=1)b=document.createElementNS("http://www.w3.org/2000/svg","circle"),b.setAttribute("cx",a*c),b.setAttribute("cy",q*c),b.setAttribute("stroke-width",0),b.setAttribute("fill",d),b.setAttribute("r",m),g.append(b)}else if("lines"==drawingHelp){c=Math.min(a,b)/15;m=Math.max(2,c/20);l=Math.round(.8*a/c)+1;n=Math.round(b/c)+1;q=Math.round(.8*a);for(a=1;a<n;a+=1){var u=document.createElementNS("http://www.w3.org/2000/svg","line");u.setAttribute("x1",0);u.setAttribute("y1",
a*c);u.setAttribute("x2",q);u.setAttribute("y2",a*c);u.setAttribute("style","stroke:"+d+";stroke-width:"+m);g.append(u)}for(q=1;q<l;q+=1)n=document.createElementNS("http://www.w3.org/2000/svg","line"),n.setAttribute("x1",q*c),n.setAttribute("y1",0),n.setAttribute("x2",q*c),n.setAttribute("y2",b),n.setAttribute("style","stroke:"+d+";stroke-width:"+m),g.append(n)}}}
function Ea(){f.children[0].style.height=x+"px";f.children[0].style.width=x+"px";document.getElementById("cursor").children[0].style.backgroundColor="rgba("+w[0]+","+w[1]+","+w[2]+",0.7)";r?O||(document.getElementById("sketchpad").classList.remove("canvas-inactive"),O=!0,jb()):Ab();var a=document.getElementById("controlspace").children;a[4].style.display="block";a[5].style.display="none";a[6].style.display="block";a[7].style.display="block";a[8].style.display="block";a[9].style.display="block";a[10].style.display=
"block";a[11].style.display="block";a[12].style.display="none";a[13].style.display="none";a[14].style.display="none";a[15].style.display="none";a[18].style.display="block";a[19].style.display="none";a[20].style.display="none";sb()}var V=-1,W=-1,X=!1,D=0,kc=null;
function Aa(a,b,c,d){-1==V?(V=b,W=c,X=!0):(X&&(Math.abs(V-b)>ra||Math.abs(W-c)>ra)||(X&&(D+=1,kc=document.createElementNS("http://www.w3.org/2000/svg","polyline"),kc.id="l"+D+"-"+username,kc.setAttribute("points",V+","+W),kc.setAttribute("style","stroke-linecap:round;fill:none;stroke:rgba("+w[0]+","+w[1]+","+w[2]+","+w[3]/255+");stroke-width:"+d),document.getElementById("sketchpad").append(kc),X=!1),kc.setAttribute("points",kc.getAttribute("points")+" "+b+","+c)),V=b,W=c)}
function Wb(a){if(0!=a){var b=document.getElementById(a);if(null!==b){b=b.getAttribute("points").split(" ");var c=[],d=-100,g=-100;if(!(5>b.length)){for(var m=0;m<b.length;m+=1){var l=b[m].split(","),n=parseInt(l[0],10);l=parseInt(l[1],10);if(Math.abs(n-d)>Fa||Math.abs(l-g)>Fa)c.push([n,l]),d=n,g=l}if(!(5>c.length)){var q=function(u,z,A,Q){z=z||u;var va=A||u;A=va[0]-z[0];z=va[1]-z[1];Q=Math.atan2(z,A)+(Q?Math.PI:0);A=.15*Math.sqrt(Math.pow(A,2)+Math.pow(z,2));return[u[0]+Math.cos(Q)*A,u[1]+Math.sin(Q)*
A]};c=c.reduce(function(u,z,A,Q){if(0===A)u="M "+z[0]+","+z[1];else{var va=q(Q[A-1],Q[A-2],z);A=q(z,Q[A-1],Q[A+1],!0);u=u+" C "+(va[0]+","+va[1]+" "+A[0]+","+A[1]+" "+z[0]+","+z[1])}return u},"");d=document.createElementNS("http://www.w3.org/2000/svg","path");b=document.getElementById(a);b.parentElement.removeChild(b);d.setAttribute("style",b.getAttribute("style"));d.setAttribute("d",c);d.id=a;document.getElementById("sketchpad").append(d)}}}}}function ec(){dc=1;k(ac,bc,cc,x)}
function gc(a){if(0!=dc&&(dc=0,X&&(lc(a),bc==V&&cc==W&&k(ac,bc,cc,x)),W=V=-1,!X)){a="l"+D+"-"+username;if(roundTable){var b=document.getElementById(a);if(null===b||null===b.getAttribute("points"))return;E.emit("send_room",{action:"line",points:b.getAttribute("points"),style:b.getAttribute("style"),id:D,username:username,room:room},function(c){y[B].timestamp=c})}Wb(a)}}function fc(a){lc(a);1==dc&&k(ac,bc,cc,x)}
function lc(a){a||(a=event);a.offsetX?(bc=a.offsetX,cc=a.offsetY):a.layerX&&(bc=a.layerX,cc=a.layerY)}function hc(a){mc(a);k(ac,T/P,U/P,x);event.preventDefault()}
function jc(a){X&&(mc(a),T==V&&U==W&&k(ac,T/P,U/P,x));W=V=-1;X||(a=document.getElementById("l"+D+"-"+username),null!==a&&null!==a.getAttribute("points")&&(roundTable&&E.emit("send_room",{action:"line",points:a.getAttribute("points"),style:a.getAttribute("style"),id:D,username:username,room:room},function(b){y[B].timestamp=b}),Wb("l"+D+"-"+username)))}function ic(a){mc(a);k(ac,T/P,U/P,x);event.preventDefault()}
function mc(a){a||(a=event);a.touches&&1==a.touches.length&&(a=a.touches[0],T=a.pageX-.1*window.innerWidth+a.target.parentElement.scrollLeft*P,U=a.pageY-a.target.parentElement.offsetTop+a.target.parentElement.scrollTop*P)}var ra=1E3;
function qa(){ra=Math.min(200,.2*Math.max(window.innerWidth*window.innerHeight));var a=document.getElementById("slidespace");a.style.height=I+"px";a.style.width=H+"px";a.style.marginLeft=.1*window.innerWidth+"px";document.body.style.fontSize=Math.round(window.innerWidth/1920*40)+"px";P=1/Math.max(H/(.8*window.innerWidth),I/window.innerHeight);a.style.fontSize=H/.8/1920*40+"px";a.style.transform="scale("+P+","+P+")";a.style.transformOrigin="top left";r&&(a=document.getElementById("sketchpad"),null==
M?(a.setAttribute("width",H+"px"),a.setAttribute("height",I+"px")):(a.setAttribute("width",M.scrollWidth+"px"),a.setAttribute("height",M.scrollHeight+"px")));fa?document.getElementById("controlspace").children[1].classList.add("fullscreenopened"):document.getElementById("controlspace").children[1].classList.remove("fullscreenopened");a=document.getElementById("zoomedim");null!==a&&(a.style.width=.8*window.innerWidth+"px",a.style.height=window.innerHeight+"px");if(a=document.getElementById("drawinghelp"))a.parentElement.removeChild(a),
sa(H/.8,I)}var Y=-1;
function db(){if(-1!=Y&&!roundTable&&(Y!=data.slides.length&&r&&(data.slides[Y].canvas=document.getElementById("sketchpad").innerHTML),Y!=data.slides.length&&null!=Y)){for(var a=[],b=document.getElementsByClassName("textannotation"),c=0;c<b.length;c+=1)null!=b[c].id&&a.push({id:b[c].id,left:b[c].style.left,top:b[c].style.top,color:b[c].style.color,maxWidth:b[c].style.maxWidth,fontSize:b[c].style.fontSize,m:b[c].innerHTML,text:b[c].dataset.s});data.slides[Y].textAnnotation=a}Y=e}
function t(a){a=void 0===a?!1:a;if(-1==e)Va();else if(null!=a&&0!=a||history.pushState("","",location.protocol+"//"+location.host+location.pathname+"#slide"+e),0==ab.length&&db(),e>=data.slides.length)v(),O=r=!1,document.getElementById("slidespace").innerHTML="<div class='cnotification'>End of presentation...<br>This presentation is made with<img src='./caroline/images/caroline2.png' class='logo'><a class='carolinelink' target='_blank' href='https://github.com/nikolasibalic/Caroline'>https://github.com/nikolasibalic/Caroline</a><br><br>open-source Python framework for interactive web/HTML-based science presentations.</div>";
else{a=""!=data.slides[e].style?"style='"+data.slides[e].style.replace("'",'"')+"'":null===logoURL?"":"style='background-image: url("+logoURL+");background-size: 13%;background-repeat: no-repeat;background-position: bottom right;background-origin: border-box;'";var b=document.getElementById("slidespace");b.innerHTML="<div class='slide'"+a+">"+data.slides[e].html+"</div>";if(null!=data.slides[e].textAnnotation){var c=data.slides[e].textAnnotation;for(a=0;a<c.length;a+=1){var d=document.createElement("div");
d.classList.add("textannotation");d.id=c[a].id;d.style.left=c[a].left;d.style.top=c[a].top;d.style.color=c[a].color;d.style.maxWidth=c[a].maxWidth;d.style.fontSize=c[a].fontSize;d.innerHTML=c[a].m;d.style.height="auto";d.style.width="auto";d.addEventListener("dblclick",wb,!1);d.dataset.s=c[a].text;b.appendChild(d)}}O?(O=r=!1,Ea()):r=!1;""!=data.slides[e].canvas&&(r||(Ab(),v()),document.getElementById("sketchpad").innerHTML=data.slides[e].canvas);pb();b=b.getElementsByClassName("simage");for(a=0;a<
b.length;a+=1)b[a].addEventListener("dblclick",function(g){var m=document.createElement("div");m.id="zoomedim";m.style.width=.8*window.innerWidth+"px";m.style.height=window.innerHeight+"px";m.innerHTML="<img src='"+g.target.src+"' class='simage' alt='zoomed figure'>";m.addEventListener("dblclick",nc,!1);document.getElementById("slidespace").append(m)}),b[a].addEventListener("mousedown",yb),b[a].setAttribute("draggable","false");document.addEventListener("dragstart",function(g){g.preventDefault()});
ab=[];b=document.getElementsByClassName("quiza");for(a=0;a<b.length;a+=1)b[a].addEventListener("click",oc);presenter&&0<b.length?(Za=b[0].dataset.qid,K.length>Za&&0<Object.keys(K[Za]).length&&$a(Za)):Za=null;pc();qc=[];rc=[];p();ta();try{MathJax.typesetClear(),MathJax.typesetPromise()}catch(g){console.log("warning: ",g)}}}
function oc(a){a=a.target;a.classList.contains("quiza")||(a=a.parentElement);a.classList.contains("selected")?a.classList.remove("selected"):a.classList.add("selected");if(!presenter){a=[];for(var b=document.getElementsByClassName("quiza"),c=b[0].dataset.qid,d=0;d<b.length;d+=1)b[d].classList.contains("selected")&&a.push(b[d].dataset.aid);J("You have selected "+a.length+" answer"+(1==a.length?"":"s")+".");E.emit("quizanswers",{to:room.substr(0,room.length-1),u:username,qid:c,a:a})}}
var rc=null,qc=[],Z=[];
function pc(){for(var a=0;a<Z.length;a+=1)null!=Z[a]&&Z[a].getTracks().forEach(function(g){"live"==g.readyState&&g.stop()});Z=[];var b=document.getElementsByClassName("demoCameraStream");for(a=0;a<b.length;a+=1){b[a].id="demostream"+a;if(b[a].dataset.src){var c=document.createElement("video");c.id="demovideo"+a;c.setAttribute("controls","");c.innerHTML='<source src="'+b[a].dataset.src+'" type="video/mp4">';b[a].append(c);var d=b[a].clientHeight;c.setAttribute("width","100%");c.setAttribute("height",
d+"px")}else Ra(b[a],sc);Z.push(null)}}
function sc(a){a.target&&(a=a.target);var b=a.parentElement.parentElement,c=parseInt(b.id.replace("demostream",""),10),d=a.dataset.l;a=a.dataset.facing;var g={video:!0};""!=d?g={video:{deviceId:{exact:d}},audio:!1}:""!=a&&(g={video:{facingMode:a},audio:!1});b.innerHTML="Adding camera...";navigator.mediaDevices&&navigator.mediaDevices.getUserMedia&&navigator.mediaDevices.getUserMedia(g).then(function(m){Z[c]=m;var l=document.createElement("video");l.id="demovideo"+c;var n=b.clientHeight;l.setAttribute("width",
b.clientWidth+"px");l.setAttribute("height",n+"px");l.style.maxHeight="100%";b.innerHTML="";b.append(l);l.srcObject=m;l.play();ta();m=document.createElement("div");m.classList.add("streamcontrol");n=document.createElement("div");n.innerHTML="Change source";n.addEventListener("click",function(){null!=Z[c]&&Z[c].getTracks().forEach(function(q){"live"==q.readyState&&q.stop()});Ra(b,sc)});m.append(n);n=document.createElement("div");n.innerHTML="Stop";n.addEventListener("click",function(){if(null!=Z[c]){l=
document.getElementById("demovideo"+c);var q=document.createElement("canvas");q.setAttribute("width",l.videoWidth+"px");q.setAttribute("height",l.videoHeight+"px");q.style.display="none";l.parentElement.append(q);q.getContext("2d").drawImage(l,0,0,l.videoWidth,l.videoHeight);q=q.toDataURL("image/png");var u=document.createElement("img");u.classList.add("simage");u.setAttribute("style",l.getAttribute("style"));u.addEventListener("mousedown",yb);u.setAttribute("draggable","false");u.setAttribute("src",
q);l.parentElement.append(u);l.style.display="none";Z[c].getTracks().forEach(function(z){"live"==z.readyState&&z.stop()})}Z[c]=null});m.append(n);b.append(m)})}function yb(a){a.preventDefault()}function tc(a){for(var b=0,c=0;c<a.length;c+=1)b=Math.max(b,a[c].offsetTop+a[c].clientHeight);return b-=window.innerHeight}
function ta(){var a=document.getElementsByClassName("slide");if(0<a.length){a=a[0].getElementsByTagName("div");var b=document.getElementsByClassName("sframe");if(0<b.length)if(0==rc.length)for(var c=0;c<b.length;c+=1)rc.push(b[c].clientHeight);else for(c=0;c<b.length;c+=1)b[c].style.maxHeight=rc[c]+"px";c=tc(a);for(var d=0;0<c&&d<b.length;)b[d].clientHeight>c&&(b[d].style.maxHeight=b[d].clientHeight-c+"px"),d+=1,c=tc(a);b=document.getElementsByClassName("demoCameraStream");if(0==qc)for(c=0;c<b.length;c+=
1)qc.push(-1);for(d=0;d<b.length;){var g=document.getElementById("demovideo"+d);g&&(-1==qc[d]?qc[d]=g.height:g.style.maxHeight=qc[d]+"px");d+=1}b=document.getElementsByClassName("demoCameraStream");d=0;for(c=tc(a);0<c&&d<b.length;)(g=document.getElementById("demovideo"+d))&&g.height>c&&(g.style.maxHeight=g.clientHeight-c+"px"),d+=1,c=tc(a)}}function pb(){for(D=0;document.getElementById("l"+(D+1)+"-"+username);)D+=1}
function nc(){var a=document.getElementById("zoomedim");a.parentElement.removeChild(a)}function Ba(){if(e<data.slides.length)if(presenter)e+=1,null!=room&&E.emit("send_room",{action:"maxslide",i:e,room:room});else if(e<G)e+=1,e==G&&J("You are following the lecturer.");else{J("You cannot go beyond lecturer in presentation. Let's keep drama alive.");return}t()}function Ca(){0==e&&presenter&&""!=presentationServer?(v(),db(),Y=-1,r=!1,e=-1,Va()):0<e&&(--e,t())}
function Vb(a){void 0==a&&(a=f);a.classList.contains("cursor_visible")&&a.classList.remove("cursor_visible");a.classList.add("cursor_hidden")}function ya(){Vb();roundTable&&E.emit("send_room",{action:"cursorhide",username:username,room:room})}function za(a){var b=a;b||(b=event);b.touches&&1==b.touches.length&&(b=b.touches[0],T=b.pageX,U=b.pageY);Tb(T,U);a.preventDefault();roundTable&&E.emit("m",{x:(T-.1*window.innerWidth)/P,y:U/P,u:username,r:room})}
function Tb(a,b,c){void 0==c&&(c=f);var d=c;void 0==d&&(d=f);d.classList.contains("cursor_hidden")&&d.classList.remove("cursor_hidden");d.classList.add("cursor_visible");c.style.transform="translate("+(a-.5*c.offsetWidth)+"px, "+(b-.5*c.offsetHeight)+"px)"}function xa(a){roundTable&&E.emit("m",{x:(a.clientX-.1*window.innerWidth)/P,y:a.clientY/P,u:username,r:room});Tb(a.clientX,a.clientY)}
function vb(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")};window.initRoundTable=function(){var a=window.location.hash.substr(1);document.getElementById("gettable").value=""==a||0==a.indexOf("slide")?"Get my roundtable":"Join roundtable";document.getElementById("uname").focus();document.getElementById("gettable").addEventListener("click",function(){null==document.getElementById("uname").value.match(/^\s+$/)&&0<document.getElementById("uname").value.length?(username=document.getElementById("uname").value,username=username.replace("=",""),document.getElementById("intro1").style.display=
"none",document.getElementById("intro2").style.display="block",document.getElementById("about").style.display="none"):document.getElementById("uname").focus()});document.getElementById("uname").addEventListener("keyup",function(c){13==(c.which||c.keyCode)&&(null==document.getElementById("uname").value.match(/^\s+$/)&&0<document.getElementById("uname").value.length?(username=document.getElementById("uname").value,username=username.replace("=",""),document.getElementById("intro1").style.display="none",
document.getElementById("intro2").style.display="block"):document.getElementById("uname").focus())});window.addEventListener("hashchange",function(){room!=window.location.hash.substr(1)&&window.location.reload()},!1);document.getElementById("bproceed").disabled=!0;document.getElementById("bproceed").addEventListener("click",function(){document.getElementById("intro2").style.display="none";document.getElementById("intro3").style.display="block";roundTableExit=function(){ca("Do you want to exit this roundtable?",
"Cancel",function(){},"Yes, leave this roundtable",function(){window.location=roundTableServer})};roundTable=!0;roundTableAuth=grecaptcha.getResponse();roundTableCallBack=da;ua();document.getElementById("controlspace").children[19].onclick=function(c){ca("Do you want to delete everything from the table (including annotations of other people)?","Cancel",function(){},"Yes, clear roundtable",function(){E.emit("send_room",{action:"clearAll",username:username,room:room});F()});c.preventDefault()};na=function(){ca("It seems you joined a roundtable where moderator already left, or lost connection.<br> Would you like to navigate to homepage and set up your own roundable?",
"No, continue waiting",function(){},"Yes, set up my own roundtable",function(){window.location=roundTableServer})}});a=document.getElementsByClassName("rselect");for(var b=0;b<a.length;b+=1)a[b].addEventListener("click",function(c){leftHanded="left hand use"==c.target.innerHTML?!0:!1;for(var d=document.getElementsByClassName("rselect"),g=0;g<d.length;g+=1)d[g].classList.remove("rselected");c.target.classList.add("rselected")})};window.initApp=ua;
window.enabaleProceed=function(){document.getElementById("bproceed").disabled=!1};window.disableProceed=function(){document.getElementById("bproceed").disabled=!0};
